enableGlobalCache: true

nodeLinker: pnp

npmAuthToken: "${NPM_DIFUKS_TOKEN:-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com/"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: 3.6.1
  typedoc@*:
    peerDependencies:
      typedoc-theme-hierarchy: "*"
  debug@*:
    dependencies:
      "supports-color": "*"

yarnPath: .yarn/releases/yarn-4.8.1.cjs
