enableGlobalCache: true

nodeLinker: pnp

npmAuthToken: "${NPM_DIFUKS_TOKEN:-}"

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.com/"

packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-theme-hierarchy: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-typescript: "3.6.1"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
